services:
  
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: garptea-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /home/ltdev/Projects/0_data/garptea-pg:/var/lib/postgresql/data
    user: ${USER_ID}:${GROUP_ID}
  
  casdoor:
    image: mycs:latest
    container_name: garptea-casdoor
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - driverName=postgres
      - "dataSourceName=user=casdoor password=casdoor host=host.docker.internal port=5432 sslmode=disable dbname=casdoor_db"
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "psyduck.home:192.168.0.105"
