services:
  
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: garptea-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    volumes:
      - ${DB_DATA_DIR}:/var/lib/postgresql/data
    user: ${USER_ID}:${GROUP_ID}
  
  casdoor:
    image: casbin/casdoor:v1.595.0
    ports:
      - 8000:8000
    environment:
      - driverName=postgres
      - dataSourceName='user=casdoor password=casdoor host=localhost port=5432 sslmode=disable dbname=casdoor_db'
    depends_on:
      - postgres